### PR TITLE
sa saddle with mirrored version

### PR DESCRIPTION
**Pull request by Geobert**
Just the sa-saddle with a mirrored version of it (2 keycaps in one file)

### CODE REVIEW

**Comment by hasufell** [comment]
are you building the lagrange?

**Comment by Geobert** [comment]
I'm planning to use these on the Sofle :)

**Comment by hasufell** [comment]
Thanks, feel free to leave a star :stuck_out_tongue_closed_eyes:

**Comment by Geobert** [comment]
Surprised I didn't already!

**Pull request merged**
